### PR TITLE
Implement train test split functionality

### PR DESCRIPTION
**Pull request by bbroeksema**
This allows for creating a train test split, so that the test split
can also be used for other evaluation

We use this to do final testing of our search engine with the
test split as well. Model training/validation is done with the
train split. Validation with the test split as well. It eases our
workflow a bit.

### CODE REVIEW

**Comment by bbroeksema** [comment]
Bump? Any feedback? Is there actually a chance of this getting merged? I'm happy to make improvements if needed, just need to know what kind of improvements you'd like to see in that case ;).

**Comment by epugh** [comment]
@softwaredoug thoughts?   It looks fine to me, though does make me start wondering if we should have unit tests and CircleCI....

**Comment by softwaredoug** [comment]
This looks pretty handy! I had been doing splitting in scripts that drive RankLib, but this seems pretty useful

**Comment by softwaredoug** [comment]
@bbroeksema BTW if you're interested in the slack channel for relevancy and our LTR projects, email me at dturnbull AT o19s DOT com and I'll invite you! Great way to get support and share ideas

**Comment by bbroeksema** [comment]
Thanks for the heads up. Email is on its way.

**Pull request merged**
